import json
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from langchain_core.messages import HumanMessage
from app.schemas.agent import AgentChatRequest, AgentStreamPayload, AgentEventType
from app.services.agent_framework.graph import compiled_graph

router = APIRouter(prefix="/agent", tags=["agent"])

async def get_current_department(token: str = "mock-token") -> str:
    return "FINANCE"

@router.post("/chat")
async def agent_chat(
    payload: AgentChatRequest,
    department: str = Depends(get_current_department)
):
    msg_text = (payload.message or "").strip().lower()
    selected_docs = payload.selected_documents or []
    
    # Ultra-Fast Path for casual greetings & direct chat turns
    import re
    clean_msg = re.sub(r'[^\w\s]', '', msg_text).strip().lower()
    GREETING_PHRASES = {"hi", "hello", "hey", "hi athena", "hello athena", "good morning", "good afternoon", "greetings", "hey athena", "yo", "howdy"}
    is_simple_greeting = clean_msg in GREETING_PHRASES

    import uuid
    async def event_generator():
        try:
            from app.services.agent_framework.supervisor import azure_llm
            from langchain_core.messages import SystemMessage, HumanMessage

            if is_simple_greeting and not selected_docs:
                greeting_response = f"Hello! I am Athena AI, your Enterprise Knowledge Assistant for the {department} department. How can I assist you with your documents or queries today?"
                words = greeting_response.split(" ")
                accum_text = ""
                import asyncio
                for w in words:
                    accum_text += (w + " ")
                    payload_dict = AgentStreamPayload(
                        event_type=AgentEventType.TOKEN,
                        node_name="final_synthesis",
                        content=accum_text.strip()
                    ).model_dump()
                    yield f"data: {json.dumps(payload_dict)}\n\n"
                    await asyncio.sleep(0.03)

                payload_dict = AgentStreamPayload(
                    event_type=AgentEventType.FINAL_RESPONSE,
                    node_name="Orchestrator",
                    content="Greeting completed.",
                    metadata={}
                ).model_dump()
                yield f"data: {json.dumps(payload_dict)}\n\n"
                return


            initial_state = {
                "messages": [HumanMessage(content=payload.message)],
                "department_boundary": department,
                "execution_plan": [],
                "next_step": "supervisor",
                "tenant_id": payload.tenant_id,
                "workspace_id": payload.workspace_id,
                "user_id": 1,
                "context_metadata": {
                    "dept_id": department, 
                    "workspace_id": payload.workspace_id,
                    "selected_documents": selected_docs
                }
            }

            unique_thread_id = str(uuid.uuid4())
            config = {"configurable": {"thread_id": unique_thread_id}}
            accumulated_tokens = ""
            final_synthesis_text = ""

            async for event in compiled_graph.astream_events(initial_state, config=config, version="v2"):
                event_type_name = event.get("event", "")
                metadata = event.get("metadata", {})
                node_name = metadata.get("langgraph_node", "")

                # ⚡️ Stream individual tokens instantly as they are generated by the LLM
                if event_type_name == "on_chat_model_stream" and node_name == "final_synthesis":
                    chunk = event.get("data", {}).get("chunk")
                    chunk_text = getattr(chunk, "content", "") if chunk else ""
                    if chunk_text and isinstance(chunk_text, str):
                        accumulated_tokens += chunk_text
                        payload_dict = AgentStreamPayload(
                            event_type=AgentEventType.TOKEN,
                            node_name="final_synthesis",
                            content=accumulated_tokens
                        ).model_dump()
                        yield f"data: {json.dumps(payload_dict)}\n\n"

                elif event_type_name == "on_chain_end" and node_name in ["final_synthesis", "rag_worker", "document_worker"]:
                    output = event.get("data", {}).get("output", {})
                    if isinstance(output, dict) and "messages" in output and output["messages"]:
                        last_msg = output["messages"][-1]
                        msg_content = getattr(last_msg, "content", str(last_msg))
                        if msg_content and "[Worker Result]" not in msg_content:
                            final_synthesis_text = msg_content
                        elif msg_content and not final_synthesis_text:
                            final_synthesis_text = msg_content

                elif event_type_name == "on_chain_start" and node_name and node_name not in ["LangGraph", "compiled_graph"]:
                    payload_dict = AgentStreamPayload(
                        event_type=AgentEventType.THOUGHT,
                        node_name=node_name,
                        content=f"Analyzing ({node_name.replace('_', ' ')})..."
                    ).model_dump()
                    yield f"data: {json.dumps(payload_dict)}\n\n"

            final_output_content = (accumulated_tokens or final_synthesis_text).strip()
            if not final_output_content:
                final_output_content = "RAG document analysis complete."

            payload_dict = AgentStreamPayload(
                event_type=AgentEventType.FINAL_RESPONSE,
                node_name="Orchestrator",
                content=final_output_content,
                metadata={}
            ).model_dump()
            yield f"data: {json.dumps(payload_dict)}\n\n"

        except Exception as e:
            yield f"data: {json.dumps({'error': str(e)})}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")