"""Add object_key and bucket to documents

Revision ID: 04114807eb5a
Revises: 91bc78d2c7df
Create Date: 2026-07-15 09:58:10.452342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04114807eb5a'
down_revision: Union[str, Sequence[str], None] = '91bc78d2c7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('object_key', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('bucket', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'bucket')
    op.drop_column('documents', 'object_key')
    # ### end Alembic commands ###
